### ISSUE TITLE
Switch to using a newer version of expand-tilde that does not use os-homedir

### ISSUE THREAD

**Issue by pravi** [jonschlinkert/resolve-dir#2]
Can you switch to using an expand-tilde version which does not depend on os-homedir? https://github.com/sindresorhus/os-homedir/issues/4 is a serious issue.

**Comment by jonschlinkert** [comment]
I thought I did. I try not to use that module, want to do a pr? Or I can fix as soon as I have a chance.

**Comment by pravi** [comment]
PR done.
